export default {
    "msg": "操作成功",
    "code": 200,
    "data": [
        {
            "roadWayId": 1,
            "roadWayName": "40101工作面辅运顺槽",
            "description": "辅运顺槽",
            "x": 16383.979540151,
            "y": 10347.9965172892,
            "workSiteInfo": []
        },
        {
            "roadWayId": 2,
            "roadWayName": "40101工作面",
            "description": "40101工作面 ",
            "x": 16238.8560841326,
            "y": 9327.01234292107,
            "workSiteInfo": []
        },
        {
            "roadWayId": 3,
            "roadWayName": "40101工作面皮带顺槽",
            "description": "",
            "x": 16402.3668874951,
            "y": 10325.076583193,
            "workSiteInfo": []
        },
        {
            "roadWayId": 4,
            "roadWayName": "副斜井",
            "description": "",
            "x": 13961.031278144,
            "y": 13463.6189533286,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 18,
                    "workSiteType": "井下基站",
                    "name": "副斜井4#倒车硐JZ24",
                    "number": 130524,
                    "parentWorkSiteNum": 0,
                    "address": "副斜井4#倒车硐",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 22140,
                        "devNum": 130524,
                        "State": "离线",
                        "StateDes": "交流供电",
                        "controlMode": "电池放电截止状态",
                        "TotalVoltage": "19482V",
                        "soc": "3.20000004768372",
                        "IpAddress": "10.1.2.168"
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 36,
                    "workSiteType": "井上基站",
                    "name": "副斜井井口JZ01",
                    "number": 131339,
                    "parentWorkSiteNum": 0,
                    "address": "副斜井井口",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 50,
                    "workSiteType": "井下基站",
                    "name": "副斜井1140米基站XJZ66",
                    "number": 131401,
                    "parentWorkSiteNum": 0,
                    "address": "副斜井1140米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 54,
                    "workSiteType": "井下基站",
                    "name": "二上辅运巷",
                    "number": 130549,
                    "parentWorkSiteNum": 0,
                    "address": "二上辅运巷",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 127,
                    "workSiteType": "井下基站",
                    "name": "130181",
                    "number": 130181,
                    "parentWorkSiteNum": 0,
                    "address": "130181",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 5,
            "roadWayName": "暗斜井",
            "description": "",
            "x": 14698.7705438764,
            "y": 12617.0253741528,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 8,
                    "workSiteType": "井下基站",
                    "name": "暗斜井600米ZJ26",
                    "number": 130526,
                    "parentWorkSiteNum": 0,
                    "address": "暗斜井600米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 2000,
                        "devNum": 130526,
                        "State": "在线",
                        "StateDes": "交流供电",
                        "controlMode": "电池放电截止状态",
                        "TotalVoltage": "",
                        "soc": "0",
                        "IpAddress": "192.168.8.1"
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 51,
                    "workSiteType": "井下基站",
                    "name": "二上暗斜井弯道XJZ67",
                    "number": 131400,
                    "parentWorkSiteNum": 0,
                    "address": "二上暗斜井弯道基站",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 52,
                    "workSiteType": "井下基站",
                    "name": "3-1暗斜井底基站",
                    "number": 131468,
                    "parentWorkSiteNum": 0,
                    "address": "3-1暗斜井底",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 1909,
                        "devNum": 131468,
                        "State": "离线",
                        "StateDes": "电池供电",
                        "controlMode": "电池放电截止状态",
                        "TotalVoltage": "",
                        "soc": "0",
                        "IpAddress": "192.168.8.22"
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 53,
                    "workSiteType": "井下基站",
                    "name": "暗斜井二中三岔口基站XJZ71",
                    "number": 131471,
                    "parentWorkSiteNum": 0,
                    "address": "暗斜井二中三岔口",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 6,
            "roadWayName": "二水平辅运",
            "description": "二水平辅运",
            "x": 14253.4654143504,
            "y": 13103.6841260393,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 48,
                    "workSiteType": "井下基站",
                    "name": "二水平中央变电室基站",
                    "number": 131469,
                    "parentWorkSiteNum": 0,
                    "address": "二水平中央变电室",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 101,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运50米JZ50",
                    "number": 131795,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运50米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 107,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运200m JZ28",
                    "number": 131760,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运200m",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 108,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运800m JZ58",
                    "number": 131763,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运800m",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 109,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运1300m  JZ30",
                    "number": 131764,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运1300m",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 7,
            "roadWayName": "二中辅运",
            "description": "二中辅运",
            "x": 14248.7029048254,
            "y": 13107.6528839768,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 10,
                    "workSiteType": "井下基站",
                    "name": "二中辅运巷JZ27",
                    "number": 130527,
                    "parentWorkSiteNum": 0,
                    "address": "二中辅运巷",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 8,
            "roadWayName": "二水平辅运1",
            "description": "二水平辅运1",
            "x": 15485.3689057349,
            "y": 11463.9588349198,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 93,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运2200米JZ43",
                    "number": 131347,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运2200米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 94,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运2800米JZ44",
                    "number": 131357,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运2800米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 100,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运3000米JZ83",
                    "number": 131343,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运3000米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 110,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运3400mJZ34",
                    "number": 131762,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运3400米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 111,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运3800米 JZ45",
                    "number": 131761,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运3800米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 115,
                    "workSiteType": "井下基站",
                    "name": "二水平辅运五联巷 JZ42",
                    "number": 131372,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运五联巷",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 12,
            "roadWayName": "40102主运",
            "description": "",
            "x": 16198.77491727,
            "y": 10635.0136841668,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 77,
                    "workSiteType": "井下基站",
                    "name": "40102综采控制台56",
                    "number": 130556,
                    "parentWorkSiteNum": 0,
                    "address": "40102综采控制台56",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 13,
            "roadWayName": "40102辅运",
            "description": "",
            "x": 16161.7643852796,
            "y": 10621.5582714966,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 69,
                    "workSiteType": "井下基站",
                    "name": "40102辅运25米XJZ84",
                    "number": 131474,
                    "parentWorkSiteNum": 0,
                    "address": "40102辅运25米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 17,
            "roadWayName": "301辅运",
            "description": "",
            "x": 14362.0425741746,
            "y": 12871.4128742646,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 38,
                    "workSiteType": "井下基站",
                    "name": "301盘区机头JZ60",
                    "number": 130560,
                    "parentWorkSiteNum": 0,
                    "address": "301盘区机头",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 49,
                    "workSiteType": "井下基站",
                    "name": "三盘区至30103路口基站",
                    "number": 131467,
                    "parentWorkSiteNum": 0,
                    "address": "三盘区至30103路口",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 18,
            "roadWayName": "主斜井",
            "description": "",
            "x": 13938.9600667787,
            "y": 13427.488092939,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 40,
                    "workSiteType": "井上基站",
                    "name": "主井口",
                    "number": 131338,
                    "parentWorkSiteNum": 0,
                    "address": "主井口",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 112,
                    "workSiteType": "井下基站",
                    "name": "主斜井440米JZ23",
                    "number": 130523,
                    "parentWorkSiteNum": 0,
                    "address": "主斜井440米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 19,
            "roadWayName": "井口检身房",
            "description": "井口检身房",
            "x": 13952.6773171744,
            "y": 13449.4561802388,
            "workSiteInfo": []
        },
        {
            "roadWayId": 20,
            "roadWayName": "独立洞室-井口检身房",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": -31347.3072152568,
            "y": 8999.62975028976,
            "workSiteInfo": []
        },
        {
            "roadWayId": 21,
            "roadWayName": "五联巷",
            "description": "",
            "x": 15560.0548089682,
            "y": 11482.7911472951,
            "workSiteInfo": []
        },
        {
            "roadWayId": 22,
            "roadWayName": "30201辅运",
            "description": "30201辅运",
            "x": 14837.3136424792,
            "y": 12375.958217269,
            "workSiteInfo": []
        },
        {
            "roadWayId": 23,
            "roadWayName": "二水平中央变电室",
            "description": "",
            "x": 15555.2333343342,
            "y": 11506.0340217099,
            "workSiteInfo": []
        },
        {
            "roadWayId": 24,
            "roadWayName": "独立洞室-二水平中央变电室",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 15569,
            "y": 11490,
            "workSiteInfo": []
        },
        {
            "roadWayId": 25,
            "roadWayName": "独立洞室-三盘区变电所",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 14383.7680561435,
            "y": 12899.8493421179,
            "workSiteInfo": []
        },
        {
            "roadWayId": 26,
            "roadWayName": "独立洞室-二中中央变电所",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 14281.5961687176,
            "y": 13087.1009538314,
            "workSiteInfo": []
        },
        {
            "roadWayId": 27,
            "roadWayName": "30202主运",
            "description": "",
            "x": 14729.2205062058,
            "y": 12680.2527119901,
            "workSiteInfo": []
        },
        {
            "roadWayId": 28,
            "roadWayName": "30201主运",
            "description": "",
            "x": 14825.7460997273,
            "y": 12330.1946734241,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 59,
                    "workSiteType": "井下基站",
                    "name": "30201机头硐室JZ77",
                    "number": 131358,
                    "parentWorkSiteNum": 0,
                    "address": "30201机头硐室",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 61,
                    "workSiteType": "井下基站",
                    "name": "30201工作面控制台JZ78",
                    "number": 131363,
                    "parentWorkSiteNum": 0,
                    "address": "30201综采工作面控制台",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 29,
            "roadWayName": "独立洞室-二中中央变电所JZ72",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 14282,
            "y": 13087,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 58,
                    "workSiteType": "井下基站",
                    "name": "二中中央变电所JZ72",
                    "number": 131348,
                    "parentWorkSiteNum": 0,
                    "address": "二中中央变电所",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 30,
            "roadWayName": "30201工作面",
            "description": "",
            "x": 15775.1068928673,
            "y": 13104.223567681,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 65,
                    "workSiteType": "井下基站",
                    "name": "30201机头Z80",
                    "number": 131369,
                    "parentWorkSiteNum": 0,
                    "address": "30201工作面机头",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": "离线",
                    "ip": "192.168.1.123",
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 66,
                    "workSiteType": "井下基站",
                    "name": "30201工作面机尾JZ81",
                    "number": 131362,
                    "parentWorkSiteNum": 0,
                    "address": "30201机尾",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 31,
            "roadWayName": "30201辅运顺槽",
            "description": "",
            "x": 14839.0121585663,
            "y": 12378.0106056845,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 62,
                    "workSiteType": "井下基站",
                    "name": "30201辅运160米JZ76",
                    "number": 130544,
                    "parentWorkSiteNum": 0,
                    "address": "30201辅运160米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 32,
            "roadWayName": "40203辅运顺槽",
            "description": "",
            "x": 17130.343351644,
            "y": 7485.24855035247,
            "workSiteInfo": []
        },
        {
            "roadWayId": 33,
            "roadWayName": "二水平东翼回风",
            "description": "",
            "x": 16804.3689053282,
            "y": 7389.72446508544,
            "workSiteInfo": []
        },
        {
            "roadWayId": 34,
            "roadWayName": "30202主运大巷",
            "description": "",
            "x": 14647.7852735742,
            "y": 12613.0066391731,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 68,
                    "workSiteType": "井下基站",
                    "name": "30202辅运通路口JZ82",
                    "number": 131368,
                    "parentWorkSiteNum": 0,
                    "address": "30202辅运通路口",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 35,
            "roadWayName": "40103机头",
            "description": "",
            "x": 15877.4798118488,
            "y": 10712.2679536077,
            "workSiteInfo": []
        },
        {
            "roadWayId": 36,
            "roadWayName": "西翼回风大巷",
            "description": "",
            "x": 16738.4345900597,
            "y": 7422.51525967045,
            "workSiteInfo": []
        },
        {
            "roadWayId": 37,
            "roadWayName": "独立洞室-二水平中央变电室JZ75",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 15569,
            "y": 11490,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 56,
                    "workSiteType": "井下基站",
                    "name": "二水平中央变电室JZ75",
                    "number": 131373,
                    "parentWorkSiteNum": 0,
                    "address": "二水平辅运中央变电室",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 38,
            "roadWayName": "独立洞室-三盘区变电所JZ73",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 14384,
            "y": 12900,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 57,
                    "workSiteType": "井下基站",
                    "name": "三盘区变电所JZ73",
                    "number": 131367,
                    "parentWorkSiteNum": 0,
                    "address": "301盘区变电所",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 39,
            "roadWayName": "40103主运",
            "description": "",
            "x": 15958.5910851407,
            "y": 10872.7525402739,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 26,
                    "workSiteType": "井下基站",
                    "name": "40103主运迎头JZ61",
                    "number": 130561,
                    "parentWorkSiteNum": 0,
                    "address": "40103主运迎头",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 40,
            "roadWayName": "40103辅运",
            "description": "",
            "x": 15940.2710447209,
            "y": 10896.5758420687,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 27,
                    "workSiteType": "井下基站",
                    "name": "40103辅运顺槽Z36",
                    "number": 130536,
                    "parentWorkSiteNum": 0,
                    "address": "40103辅运顺槽Z36",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 41,
            "roadWayName": "二水平永久避难硐室",
            "description": "",
            "x": 15533.775235509,
            "y": 11492.1433623889,
            "workSiteInfo": []
        },
        {
            "roadWayId": 42,
            "roadWayName": "独立洞室-二水平永久避难硐室JZ40",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 15534.410236779,
            "y": 11492.6196133414,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 71,
                    "workSiteType": "井下基站",
                    "name": "二水平永久避难硐室JZ40",
                    "number": 130540,
                    "parentWorkSiteNum": 0,
                    "address": "二水平永久避难硐室",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 43,
            "roadWayName": "40201回风通路",
            "description": "",
            "x": 17517.6143523303,
            "y": 7472.89368337675,
            "workSiteInfo": []
        },
        {
            "roadWayId": 44,
            "roadWayName": "二水平主运大巷",
            "description": "",
            "x": 14385.3196254823,
            "y": 12875.3250562413,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 102,
                    "workSiteType": "井下基站",
                    "name": "二水平主运1300米 JZ51",
                    "number": 130550,
                    "parentWorkSiteNum": 0,
                    "address": "二水平主运1300米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 103,
                    "workSiteType": "井下基站",
                    "name": "二水平主运1800米 JZ53",
                    "number": 130530,
                    "parentWorkSiteNum": 0,
                    "address": "二水平主运1800米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 104,
                    "workSiteType": "井下基站",
                    "name": "二水平主运2400米 JZ54",
                    "number": 130528,
                    "parentWorkSiteNum": 0,
                    "address": "二水平主运2400米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 105,
                    "workSiteType": "井下基站",
                    "name": "二水平主运2950米 JZ55",
                    "number": 130534,
                    "parentWorkSiteNum": 0,
                    "address": "二水平主运2950米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 106,
                    "workSiteType": "井下基站",
                    "name": "二水平主运3600米 JZ57",
                    "number": 130545,
                    "parentWorkSiteNum": 0,
                    "address": "二水平主运3600米",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 45,
            "roadWayName": "30202工作面切眼",
            "description": "",
            "x": 15700.1049476073,
            "y": 13463.5679362473,
            "workSiteInfo": []
        },
        {
            "roadWayId": 46,
            "roadWayName": "40102工作面",
            "description": "",
            "x": 14626.9095338511,
            "y": 7519.46213468985,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 78,
                    "workSiteType": "井下基站",
                    "name": "40102工作面机头jz35",
                    "number": 130535,
                    "parentWorkSiteNum": 0,
                    "address": "40102工作面机头",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                },
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 79,
                    "workSiteType": "井下基站",
                    "name": "40102工作面机尾JZ41",
                    "number": 130541,
                    "parentWorkSiteNum": 0,
                    "address": "40102工作面机尾",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 47,
            "roadWayName": "独立洞室-风井安全出口JZ89",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 13923,
            "y": 13394,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 80,
                    "workSiteType": "井上基站",
                    "name": "风井安全出口JZ89",
                    "number": 131475,
                    "parentWorkSiteNum": 0,
                    "address": "风井安全出口",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 48,
            "roadWayName": "独立洞室-回风立井JZ92",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 15970,
            "y": 10794,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 81,
                    "workSiteType": "井上基站",
                    "name": "回风立井JZ92",
                    "number": 131472,
                    "parentWorkSiteNum": 0,
                    "address": "回风立井",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 49,
            "roadWayName": "二上辅运",
            "description": "",
            "x": 14736.8824844466,
            "y": 12506.2659119604,
            "workSiteInfo": []
        },
        {
            "roadWayId": 50,
            "roadWayName": "二上辅运1",
            "description": "",
            "x": 14726.1780691584,
            "y": 12488.6645474713,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 83,
                    "workSiteType": "井下基站",
                    "name": "201配电点XJZ94",
                    "number": 131473,
                    "parentWorkSiteNum": 0,
                    "address": "201配电点",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 51,
            "roadWayName": "40203工作面回撤通道",
            "description": "",
            "x": 17104.04134801,
            "y": 7607.63461667969,
            "workSiteInfo": []
        },
        {
            "roadWayId": 52,
            "roadWayName": "2#进风通路",
            "description": "",
            "x": 17037.9223549446,
            "y": 7135.28637014199,
            "workSiteInfo": []
        },
        {
            "roadWayId": 53,
            "roadWayName": "二中辅回一联巷",
            "description": "",
            "x": 14323.4776614963,
            "y": 13012.2493457781,
            "workSiteInfo": []
        },
        {
            "roadWayId": 54,
            "roadWayName": "二中辅运2",
            "description": "",
            "x": 14647.32405644,
            "y": 12598.8501877025,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 82,
                    "workSiteType": "井下基站",
                    "name": "203配电点XJZ93",
                    "number": 131402,
                    "parentWorkSiteNum": 0,
                    "address": "203配电点",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 55,
            "roadWayName": "40104外回风顺槽",
            "description": "",
            "x": 15729.5912148395,
            "y": 10756.9652696255,
            "workSiteInfo": []
        },
        {
            "roadWayId": 56,
            "roadWayName": "地面",
            "description": "",
            "x": 13971.8602639272,
            "y": 13474.6330788824,
            "workSiteInfo": []
        },
        {
            "roadWayId": 57,
            "roadWayName": "独立洞室-地面候车室",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 13972.0190142447,
            "y": 13474.7918291999,
            "workSiteInfo": []
        },
        {
            "roadWayId": 58,
            "roadWayName": "独立洞室-地面候车室1",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 13972.6379656943,
            "y": 13472.0152288393,
            "workSiteInfo": []
        },
        {
            "roadWayId": 59,
            "roadWayName": "独立洞室-候车室234",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 13977.8392282388,
            "y": 13466.3964735319,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 91,
                    "workSiteType": "井上基站",
                    "name": "候车室234",
                    "number": 131429,
                    "parentWorkSiteNum": 0,
                    "address": "候车室",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 60,
            "roadWayName": "30203工作面切眼",
            "description": "",
            "x": 15415.9160875493,
            "y": 13463.1286080388,
            "workSiteInfo": []
        },
        {
            "roadWayId": 61,
            "roadWayName": "402盘区东翼主运大巷",
            "description": "",
            "x": 16810.800008089,
            "y": 7427.5636062598,
            "workSiteInfo": []
        },
        {
            "roadWayId": 62,
            "roadWayName": "40203主运大巷",
            "description": "",
            "x": 17106.7201759869,
            "y": 7611.63826833329,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 28,
                    "workSiteType": "井下基站",
                    "name": "40203主运JZ52",
                    "number": 130552,
                    "parentWorkSiteNum": 0,
                    "address": "40203主运",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 63,
            "roadWayName": "独立洞室-二水平机头JZ88",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 14404.1203025093,
            "y": 12864.0515809178,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 114,
                    "workSiteType": "井下基站",
                    "name": "二水平机头JZ88",
                    "number": 130543,
                    "parentWorkSiteNum": 0,
                    "address": "二水平机头",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 64,
            "roadWayName": "402盘区变电所",
            "description": "",
            "x": 16808.1490794661,
            "y": 7466.82918886316,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 25,
                    "workSiteType": "井下基站",
                    "name": "402盘区变电所JZ62",
                    "number": 130562,
                    "parentWorkSiteNum": 0,
                    "address": "402盘区变电所",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        },
        {
            "roadWayId": 65,
            "roadWayName": "独立洞室-301盘区避难硐室JZ33",
            "description": "独立洞室:不需要手动添加在基站添加时勾选默认自动添加",
            "x": 14348.0285236591,
            "y": 12944.1146577106,
            "workSiteInfo": [
                {
                    "DevType": 0,
                    "IsVehicleLocation": 0,
                    "LocType": 0,
                    "id": 119,
                    "workSiteType": "井下基站",
                    "name": "301盘区避难硐室JZ33",
                    "number": 130533,
                    "parentWorkSiteNum": 0,
                    "address": "301盘区避难硐室",
                    "status": 0,
                    "chip": null,
                    "type": 0,
                    "ControllerNum": 0,
                    "CommType": 6,
                    "RoadWayId": 0,
                    "RoadWayName": null,
                    "feederlineLen": 0,
                    "IsCorrecting": 0,
                    "CorrectingType": 0,
                    "AllCheckLen": null,
                    "CommTypeName": "高精度主站",
                    "state": null,
                    "ip": null,
                    "powerInfo": {
                        "powerId": 0,
                        "devNum": 0,
                        "State": null,
                        "StateDes": null,
                        "controlMode": null,
                        "TotalVoltage": null,
                        "soc": null,
                        "IpAddress": null
                    }
                }
            ]
        }
    ]
}